FROM python:3.9.13-buster

RUN python3 -m venv /opt/venv

WORKDIR /usr/app/src

COPY requirements.txt ./
RUN /opt/venv/bin/pip install -r requirements.txt

COPY allocate_nfts.py ./
ENTRYPOINT ["/opt/venv/bin/python3", "./allocate_nfts.py"]